### ISSUE TITLE
what is args.use_sto

### ISSUE THREAD

**Issue by chg0901** [Li-Wanhua/POEs#3]
Could you please what is the meaning of this parameter? I didn't find it defination from the .sh script

https://github.com/Li-Wanhua/POEs/blob/f8efd3daa9bbb2abdaae61ed93c487d6de98968d/codes/adience_poe/scripts/train_poe.sh#L33-L49

https://github.com/Li-Wanhua/POEs/blob/f8efd3daa9bbb2abdaae61ed93c487d6de98968d/codes/adience_poe/train.py#L37-L46

https://github.com/Li-Wanhua/POEs/blob/f8efd3daa9bbb2abdaae61ed93c487d6de98968d/codes/adience_poe/train.py#L96-L105

**Comment by Li-Wanhua** [comment]
It is used to indicate whether or not probabilistic embeddings are used. When args.use_sto=True, we use probabilistic embeddings. When args.use_sto=False, our code runs with deterministic embeddings.
