### ISSUE TITLE
problem in probordiloss.py

### ISSUE THREAD

**Issue by xuangch** [Li-Wanhua/POEs#4]
The #95 line in this file should use repeat_interleave instead of repeat？Since the sample size is the first dimension of logit.
Thanks.

**Comment by xk-huang** [comment]
Hi! Do you mean this code snippet?
https://github.com/Li-Wanhua/POEs/blob/main/codes/adience_poe/poe/probordiloss.py#L94-L95
As `target` is only a scalar tensor, so using `repeat_interleave` or `repeat`, or even `expand` (speed matters!) is the same in this case

**Comment by xuangch** [comment]
Thank you for your reply!
Yep. I think that target should be a 1D tensor which length is the batch size ? In this case, repeat_interleave and repeat return different result. Did I think wrong?

**Comment by xk-huang** [comment]
Oh,I got ya! In fact the first dim is the sampling dim (`max_t = 50`) rather than the batch size dim.
https://github.com/Li-Wanhua/POEs/blob/main/codes/adience_poe/poe/vgg.py#L72-L74
```python
(Pdb) logit.shape
torch.Size([50, 32, 1])
(Pdb) logit.view(-1).shape
torch.Size([1600])
(Pdb) target.repeat(sample_size).shape
torch.Size([1600])
(Pdb) target.shape
torch.Size([32])
```

**Comment by xuangch** [comment]
Yes.  As a example, if target is [1, 2, 3], then torch.repeat(2) return [1, 2, 3, 1, 2, 3] but torch.repeat_interleave(2) return [1, 1, 2, 2, 3, 3]. I think the latter should be right.

**Comment by xk-huang** [comment]
In https://github.com/Li-Wanhua/POEs/blob/main/codes/adience_poe/poe/vgg.py#L72-L74 we use `expand` here
so in the loss part we use the tensor repeat method with the same semantic meaning
```python
In [13]: a = torch.arange(3)

a[None].expand(2, 3).reshape(-1)
Out[14]: tensor([0, 1, 2, 0, 1, 2])

In [15]: a.repeat(2)
Out[15]: tensor([0, 1, 2, 0, 1, 2])

In [16]: torch.repeat_interleave(a,2)
Out[16]: tensor([0, 0, 1, 1, 2, 2])
```

**Comment by xuangch** [comment]
Oh I understand! I have made a moronic mistake 😂 . Thank you for your reply！
